/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ulabs.poo_week6.gui;

import com.ulabs.poo_week6.children.Student;
import com.ulabs.poo_week6.children.Teacher;
import javax.swing.JOptionPane;

/**
 *
 * @author manuelguarniz
 */
public class Application extends javax.swing.JFrame {

    /**
     * Creates new form Application
     */
    public Application() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTeacherName = new javax.swing.JTextField();
        txtTeacherAge = new javax.swing.JTextField();
        txtTeacherLastname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTeacherHoursWorked = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTeacherFee = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtStudentFirstname = new javax.swing.JTextField();
        txtStudentAge = new javax.swing.JTextField();
        txtStudentLastname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtStudentNote1 = new javax.swing.JTextField();
        txtStudentNote3 = new javax.swing.JTextField();
        txtStudentNote2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnProcess = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtStudentResume = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTeacherResume = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Docente"));

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellidos:");

        jLabel4.setText("Edad:");

        txtTeacherAge.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTeacherAgeFocusLost(evt);
            }
        });

        jLabel9.setText("Tarifa:");

        txtTeacherHoursWorked.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTeacherHoursWorkedFocusLost(evt);
            }
        });

        jLabel10.setText("Horas trabajadas:");

        txtTeacherFee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTeacherFeeFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTeacherName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTeacherLastname)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtTeacherAge, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(txtTeacherFee, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(10, 10, 10))
                                    .addComponent(txtTeacherHoursWorked))))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTeacherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTeacherLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTeacherAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTeacherHoursWorked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTeacherFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Ejercicio Semana 6");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Alumno"));

        jLabel5.setText("Nombre:");

        jLabel6.setText("Apellidos:");

        jLabel7.setText("Edad:");

        txtStudentAge.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtStudentAgeFocusLost(evt);
            }
        });

        jLabel8.setText("Nota 1:");

        txtStudentNote1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtStudentNote1FocusLost(evt);
            }
        });

        txtStudentNote3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtStudentNote3FocusLost(evt);
            }
        });

        txtStudentNote2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtStudentNote2FocusLost(evt);
            }
        });

        jLabel11.setText("Nota 2:");

        jLabel12.setText("Nota 3:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStudentFirstname, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtStudentAge, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtStudentLastname)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStudentNote1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStudentNote2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtStudentNote3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStudentFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtStudentLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStudentAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStudentNote1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStudentNote3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStudentNote2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnProcess.setText("Procesar");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessClick(evt);
            }
        });

        txtStudentResume.setColumns(20);
        txtStudentResume.setRows(5);
        txtStudentResume.setPreferredSize(new java.awt.Dimension(200, 80));
        jScrollPane1.setViewportView(txtStudentResume);

        txtTeacherResume.setColumns(20);
        txtTeacherResume.setRows(5);
        jScrollPane2.setViewportView(txtTeacherResume);

        jLabel13.setText("Resumen Docente:");

        jLabel14.setText("Resumen Alumno:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel14)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(btnProcess))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel13)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProcess)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessClick
        String teacherFirstname = txtTeacherName.getText();
        String teacherLastname = txtTeacherLastname.getText();
        Integer teacherAge = Integer.parseInt(txtTeacherAge.getText());
        Integer teacherFee = Integer.parseInt(txtTeacherFee.getText());
        Double teacherHoursWorked = Double.parseDouble(txtTeacherHoursWorked.getText());
        
        Teacher teacher = new Teacher(teacherFirstname, teacherLastname, teacherAge,
                                        teacherFee, teacherHoursWorked);
        
        String studentFirstname = txtStudentFirstname.getText();
        String studentLastname = txtStudentLastname.getText();
        Integer studentAge = Integer.parseInt(txtStudentAge.getText());
        Double studentNote1 = Double.parseDouble(txtStudentNote1.getText());
        Double studentNote2 = Double.parseDouble(txtStudentNote2.getText());
        Double studentNote3 = Double.parseDouble(txtStudentNote3.getText());
        
        Student student = new Student(studentFirstname, studentLastname, studentAge,
                studentNote1, studentNote2, studentNote3);
        
        txtTeacherResume.setText(teacher.showInformation());
        txtStudentResume.setText(student.showInformation());
        
    }//GEN-LAST:event_btnProcessClick

    private void txtTeacherFeeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTeacherFeeFocusLost
        try {
            if (txtTeacherFee.getText() != null && !txtTeacherFee.getText().equalsIgnoreCase("")) {
                Double fee = Double.parseDouble(txtTeacherFee.getText());
                if (fee < 0) {
                    JOptionPane.showMessageDialog(null, "Tarifa debe ser mayor que 0 !");
                    txtTeacherFee.requestFocus();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tarifa es invalido !");
            txtTeacherFee.requestFocus();
        }
    }//GEN-LAST:event_txtTeacherFeeFocusLost

    private void txtTeacherHoursWorkedFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTeacherHoursWorkedFocusLost
        try {
            if (txtTeacherHoursWorked.getText() != null && !txtTeacherHoursWorked.getText().equalsIgnoreCase("")) {
                Integer hoursWorked = Integer.parseInt(txtTeacherHoursWorked.getText());
                if (hoursWorked < 0) {
                    JOptionPane.showMessageDialog(null, "Horas trabajada deben ser mayor que 0 !");
                    txtTeacherHoursWorked.requestFocus();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Horas trabajadas es invalido !");
            txtTeacherHoursWorked.requestFocus();
        }
    }//GEN-LAST:event_txtTeacherHoursWorkedFocusLost

    private void txtStudentNote1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStudentNote1FocusLost
        try {
            if (txtStudentNote1.getText() != null && !txtStudentNote1.getText().equalsIgnoreCase("")) {
                Double note = Double.parseDouble(txtStudentNote1.getText());
                if (note < 0 || note > 20) {
                    JOptionPane.showMessageDialog(null, "Nota1 debe ser entre 0 y 20 !");
                    txtStudentNote1.requestFocus();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Nota1 es invalido !");
            txtStudentNote1.requestFocus();
        }
    }//GEN-LAST:event_txtStudentNote1FocusLost

    private void txtStudentNote2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStudentNote2FocusLost
        try {
            if (txtStudentNote2.getText() != null && !txtStudentNote2.getText().equalsIgnoreCase("")) {
                Double note = Double.parseDouble(txtStudentNote2.getText());
                if (note < 0 || note > 20) {
                    JOptionPane.showMessageDialog(null, "Nota2 debe ser entre 0 y 20 !");
                    txtStudentNote2.requestFocus();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Nota2 es invalido !");
            txtStudentNote2.requestFocus();
        }
    }//GEN-LAST:event_txtStudentNote2FocusLost

    private void txtStudentNote3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStudentNote3FocusLost
        try {
            if (txtStudentNote3.getText() != null && !txtStudentNote3.getText().equalsIgnoreCase("")) {
                Double note = Double.parseDouble(txtStudentNote3.getText());
                if (note < 0 || note > 20) {
                    JOptionPane.showMessageDialog(null, "Nota3 debe ser entre 0 y 20 !");
                    txtStudentNote3.requestFocus();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Nota3 es invalido !");
            txtStudentNote3.requestFocus();
        }
    }//GEN-LAST:event_txtStudentNote3FocusLost

    private void txtTeacherAgeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTeacherAgeFocusLost
        try {
            if (txtTeacherAge.getText() != null && !txtTeacherAge.getText().equalsIgnoreCase("")) {
                Integer age = Integer.parseInt(txtTeacherAge.getText());
                if (age < 18) {
                    JOptionPane.showMessageDialog(null, "Es menor de edad !");
                    txtTeacherAge.requestFocus();
                } else if (age > 65) {
                    JOptionPane.showMessageDialog(null, "Ya es hora de jubilarse !");
                    txtTeacherAge.requestFocus();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Edad es invalido !");
            txtTeacherAge.requestFocus();
        }
    }//GEN-LAST:event_txtTeacherAgeFocusLost

    private void txtStudentAgeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStudentAgeFocusLost
        try {
            if (txtStudentAge.getText() != null && !txtStudentAge.getText().equalsIgnoreCase("")) {
                Integer age = Integer.parseInt(txtStudentAge.getText());
                if (age < 15) {
                    JOptionPane.showMessageDialog(null, "Muy joven para estudiar en la Universidad !");
                    txtStudentAge.requestFocus();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Edad es invalido !");
            txtStudentAge.requestFocus();
        }
    }//GEN-LAST:event_txtStudentAgeFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Application app = new Application();
                app.setVisible(true);
                app.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnProcess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtStudentAge;
    private javax.swing.JTextField txtStudentFirstname;
    private javax.swing.JTextField txtStudentLastname;
    private javax.swing.JTextField txtStudentNote1;
    private javax.swing.JTextField txtStudentNote2;
    private javax.swing.JTextField txtStudentNote3;
    private javax.swing.JTextArea txtStudentResume;
    private javax.swing.JTextField txtTeacherAge;
    private javax.swing.JTextField txtTeacherFee;
    private javax.swing.JTextField txtTeacherHoursWorked;
    private javax.swing.JTextField txtTeacherLastname;
    private javax.swing.JTextField txtTeacherName;
    private javax.swing.JTextArea txtTeacherResume;
    // End of variables declaration//GEN-END:variables
}
